/**
 * @fileoverview gRPC-Web generated client stub for reporting
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v7.35.0
// source: Transaction.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as Transaction_pb from './Transaction_pb'; // proto import: "Transaction.proto"


export class TransactionServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStreamTransactions = new grpcWeb.MethodDescriptor(
    '/reporting.TransactionService/StreamTransactions',
    grpcWeb.MethodType.SERVER_STREAMING,
    Transaction_pb.ReportRequest,
    Transaction_pb.TransactionResponse,
    (request: Transaction_pb.ReportRequest) => {
      return request.serializeBinary();
    },
    Transaction_pb.TransactionResponse.deserializeBinary
  );

  streamTransactions(
    request: Transaction_pb.ReportRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<Transaction_pb.TransactionResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/reporting.TransactionService/StreamTransactions',
      request,
      metadata || {},
      this.methodDescriptorStreamTransactions);
  }

}

